### ISSUE TITLE
$$restProps is not a valid property name for Svelte v3.1x and less

### ISSUE THREAD

**Issue by jack-y** [xnimorz/svelte-input-mask#9]
In the `MaskInput.svelte` component, you should use the property name `$$props` instead of `$$restProps`, which is not valid. `$$restProps` fires an error:

```
Error: Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ValidationError: $$restProps is an illegal variable name (174:6)
```

**Comment by xnimorz** [comment]
Hi @jack-y. Thank you for the question.

`svelte-input-mask` requires `svelte>=3.20.0` at least (https://github.com/xnimorz/svelte-input-mask/blob/master/package.json#L41-L43 it should be a warning when you try to install this package) as this version has `$$restProps` param. 
This param is better than `$$props` param because it allows you to update the component when any param inside `$$restProps` is changed.

Some refs related to `$$restProps`: 
1) https://svelte.dev/docs#Attributes_and_props (`$$restProps` section)
2) https://github.com/sveltejs/svelte/issues/2930 — here you could read several issues related to this
3) https://github.com/xnimorz/svelte-input-mask/issues/5

Please, check the svelte version in your project.

**Comment by jack-y** [comment]
Hi @xnimorz,

Thank you for your quick answer. You're right, and your explaination is great.

I've change my svelte version and everything is fine.
Accordingly, the title of this issue is changed.

I think it would be more understandable if you specify the required version of svelte in your README file.

**Comment by xnimorz** [comment]
Added https://github.com/xnimorz/svelte-input-mask/commit/7e752b74084580e6c189fabd1efef09221cb5ae0
